import Icon from './Icon.jsx';

const prompts = [
  { label: 'Learn a concept', text: 'Explain closures in JavaScript', icon: 'sparkles' },
  { label: 'Debug my code', text: 'Help me debug this React code', icon: 'edit' },
  { label: 'Prepare for an interview', text: 'Prepare me for a frontend interview', icon: 'file' },
  { label: 'Explore a topic', text: 'Explain recursion with an example', icon: 'search' },
];

function EmptyChat({ onPromptSelect }) {
  return <div className="empty-chat">
    <div className="empty-orb" aria-hidden="true"><span className="orb-star orb-star--one"><Icon name="sparkles" size={23} /></span><span className="orb-star orb-star--two"><Icon name="sparkleSmall" size={12} /></span><span className="orb-core"><Icon name="sparkles" size={32} /></span></div>
    <p className="eyebrow">Your thinking partner</p>
    <h1>What can I help you <em>build</em> today?</h1>
    <p className="empty-description">Ask questions, explore ideas, or work through a problem. Nexa is here to help you think more clearly.</p>
    <div className="prompt-grid" aria-label="Suggested prompts">{prompts.map((prompt) => <button className="prompt-card" type="button" key={prompt.text} onClick={() => onPromptSelect(prompt.text)}><span className="prompt-icon"><Icon name={prompt.icon} size={17} /></span><span><small>{prompt.label}</small><strong>{prompt.text}</strong></span><span className="prompt-arrow">↗</span></button>)}</div>
    <p className="empty-note"><Icon name="check" size={13} /> Responses are generated by Nexa AI · Always review important information</p>
  </div>;
}

export default EmptyChat;
